#!/usr/bin/env ansible-playbook
---
- name: Initializing Configuration
  hosts: localhost
  connection: local
  become: false
  gather_facts: no
  any_errors_fatal: true

  tasks:

    - set_fact:
        esx_template_location: "{{ template_map[buildInfo.esx] }}"
        vcsa_template_location: "{{ template_map[buildInfo.vcsa] }}"
        vcsa_template_prefix: "{{ template_map[buildInfo.vcsa].split('/')[4] }}"
        esx_template_prefix: "{{ template_map[buildInfo.esx].split('/')[4] }}"
        witness_template_prefix: "{{ template_map['witness'].split('/')[4] }}"
        controller_template_prefix: "{{ template_map[buildInfo.scvm].split('/')[4] }}"
        replRoleType: "{{ cluster.replRoleType | default(omit, True) | lower }}"
        powerVMS: "{{ powerVMS | default(true) }}"

    - name: Set Template Name
      set_fact:
        template_name: "{{ jsonData.deploy.vcCluster }}-{{ esx_template_prefix }}"
        vcsa_template: "{{ jsonData.deploy.vcCluster }}-{{ vcsa_template_prefix }}"
        cvm_template: "{{ jsonData.deploy.vcCluster }}-{{ controller_template_prefix }}-controller"
        witness_name: "{{ witness_template_prefix }}-{{ userId }}-{{ cluster.name }}-{{ jsonData.deploy.vmPrefix }}"
        buildUrl: "http://buildweb.eng.storvisor.com/master/untested-builds/latest/release"

    - set_fact:
        vcsa_name: "{{ vcsa_template_prefix }}-{{ userId }}-{{ jsonData.deploy.vmPrefix }}-source"

    - set_fact:
        vcsa_name: "{{ vcsa_template_prefix }}-{{ userId }}-{{ jsonData.deploy.vmPrefix }}-target"
      when: replRoleType is defined and replRoleType == 'target'

    - name: Get Build Info
      set_fact:
        storfsRelease: "2.5.1a"
        storfsBuild: "10000"
        package: "stofs-packages.tar.gz"
      # local_action:
      #   module: getbuild.py
      #   url: "{{ buildUrl }}"

    - name: Get IP Information
      local_action:
        module: reserve.py
        clusterInfo: "{{ cluster }}"
        jsonData: "{{ jsonData }}"
        release: "{{ storfsRelease }}"
        userId: "{{ userId }}"

    - name: Get VCSA IP
      local_action:
        module: reserve.py
        jsonData: "{{ jsonData }}"
        node: "{{ vcsa_name }}"

    - name: extract esx host info
      add_host: name={{ item.hypervisorMgmt }} group=esx
                ansible_user={{ jsonData.deploy.user }}
                ansible_ssh_pass={{ jsonData.esx.password | b64decode }}
                ansible_pass={{ jsonData.esx.password | b64decode }}
                esxip={{ item.hypervisorMgmt }}
                scvmip={{ item.controllerMgmt }}
                hypervisorip={{ item.hypervisorData }}
                scvmdataip={{ item.controllerData }}
                clusterName={{ item.clusterName }}
                datacenter={{ item.datacenter }}
                mgmtcip={{ item.mgmtcip }}
                datacip={{ item.datacip }}
                nodecount={{ item.nodecount }}
                storfsBuild={{ storfsBuild }}
                storfsRelease={{ storfsRelease }}
                package={{ package }}
      with_items:
          - "{{ nodes.values() }}"

    - name: extract controller info
      add_host: name={{ item.controllerMgmt }} group=controllers
                ansible_user={{ jsonData.deploy.user }}
                ansible_ssh_pass={{ jsonData.esx.password | b64decode }}
                ansible_pass={{ jsonData.esx.password | b64decode }}
                esx_host={{ item.hypervisorMgmt }}
                scvmip={{ item.controllerMgmt }}
                hypervisorip={{ item.hypervisorData }}
                dataip={{ item.controllerData }}
                clusterName={{ item.clusterName }}
                datacenter={{ item.datacenter }}
                mgmtcip={{ item.mgmtcip }}
                datacip={{ item.datacip }}
                nodecount={{ item.nodecount }}
                storfsBuild={{ storfsBuild }}
                storfsRelease={{ storfsRelease }}
                package={{ package }}
                replip={{ item.controllerRepl }}
                replcip={{ item.replcip }}
      with_items:
          - "{{ nodes.values() }}"

    - name: extract cluster info
      add_host: name={{ item.mgmtcip }} group=clusters
                ansible_user={{ jsonData.deploy.user }}
                ansible_ssh_pass={{ jsonData.esx.password | b64decode }}
                ansible_pass={{ jsonData.esx.password | b64decode }}
                esx_host={{ item.hypervisorMgmt }}
                scvmip={{ item.controllerMgmt }}
                hypervisorip={{ item.hypervisorData }}
                dataip={{ item.controllerData }}
                clusterName={{ item.clusterName }}
                datacenter={{ item.datacenter }}
                mgmtcip={{ item.mgmtcip }}
                datacip={{ item.datacip }}
                nodecount={{ item.nodecount }}
                storfsBuild={{ storfsBuild }}
                storfsRelease={{ storfsRelease }}
                package={{ package }}
                vcsaIp={{ vcsaIp | default(jsonData.vcenter.host) }}
      with_items:
          - "{{ nodes.values() }}"

    - name: Revert to a snapshot
      local_action:
        module: vmware_guest_snapshot
        hostname: "{{ jsonData.deploy.vcHost }}"
        username: "{{ jsonData.deploy.vcUser }}"
        password: "{{ jsonData.deploy.vcPass }}"
        validate_certs: no
        name: "{{ vcsa_name }}"
        datacenter: "{{ jsonData.deploy.vcDatacenter }}"
        folder: "/{{ jsonData.deploy.vcDatacenter }}/vm/{{ jsonData.deploy.vcCluster }}-simulators"
        state: revert
        snapshot_name: clean
      when: powerVMS

    - name: Power on VM
      local_action:
        module: vmware_guest
        hostname: "{{ jsonData.deploy.vcHost }}"
        username: "{{ jsonData.deploy.vcUser }}"
        password: "{{ jsonData.deploy.vcPass }}"
        validate_certs: no
        cluster: "{{ jsonData.deploy.vcCluster }}"
        datacenter: "{{ jsonData.deploy.vcDatacenter }}"
        folder: "/{{ jsonData.deploy.vcDatacenter }}/vm/{{ jsonData.deploy.vcCluster }}-simulators"
        name: "{{ vcsa_name }}"
        state: poweredon
      when: powerVMS

    - name: Power off VM
      local_action:
        module: vmware_guest
        hostname: "{{ jsonData.deploy.vcHost }}"
        username: "{{ jsonData.deploy.vcUser }}"
        password: "{{ jsonData.deploy.vcPass }}"
        validate_certs: no
        cluster: "{{ jsonData.deploy.vcCluster }}"
        datacenter: "{{ jsonData.deploy.vcDatacenter }}"
        folder: "/{{ jsonData.deploy.vcDatacenter }}/vm/{{ jsonData.deploy.vcCluster }}-simulators"
        name: "{{ vcsa_name }}"
        state: poweredoff
      when: not powerVMS

    - name: Revert to a snapshot
      local_action:
        module: vmware_guest_snapshot
        hostname: "{{ jsonData.deploy.vcHost }}"
        username: "{{ jsonData.deploy.vcUser }}"
        password: "{{ jsonData.deploy.vcPass }}"
        validate_certs: no
        name: "{{ witness_name }}"
        datacenter: "{{ jsonData.deploy.vcDatacenter }}"
        folder: "/{{ jsonData.deploy.vcDatacenter }}/vm/{{ jsonData.deploy.vcCluster }}-simulators"
        state: revert
        snapshot_name: clean
      when: powerVMS and (replRoleType is defined and replRoleType == 'stretch')

    - name: Power on VM
      local_action:
        module: vmware_guest
        hostname: "{{ jsonData.deploy.vcHost }}"
        username: "{{ jsonData.deploy.vcUser }}"
        password: "{{ jsonData.deploy.vcPass }}"
        validate_certs: no
        cluster: "{{ jsonData.deploy.vcCluster }}"
        datacenter: "{{ jsonData.deploy.vcDatacenter }}"
        folder: "/{{ jsonData.deploy.vcDatacenter }}/vm/{{ jsonData.deploy.vcCluster }}-simulators"
        name: "{{ witness_name }}"
        state: poweredon
      when: powerVMS and (replRoleType is defined and replRoleType == 'stretch')

    - name: Power off VM
      local_action:
        module: vmware_guest
        hostname: "{{ jsonData.deploy.vcHost }}"
        username: "{{ jsonData.deploy.vcUser }}"
        password: "{{ jsonData.deploy.vcPass }}"
        validate_certs: no
        cluster: "{{ jsonData.deploy.vcCluster }}"
        datacenter: "{{ jsonData.deploy.vcDatacenter }}"
        folder: "/{{ jsonData.deploy.vcDatacenter }}/vm/{{ jsonData.deploy.vcCluster }}-simulators"
        name: "{{ witness_name }}"
        state: poweredoff
      when: not powerVMS and (replRoleType is defined and replRoleType == 'stretch')


- name: Configure ESX
  hosts: esx
  become: false
  gather_facts: no
  any_errors_fatal: true

  tasks:

    - set_fact:
        vm_name: "{{ jsonData.deploy.vmPrefix }}-{{ userId }}-{{ hostvars[inventory_hostname]['clusterName'] }}-{{ inventory_hostname }}"
        cvm_name: "stCtlVM-{{ userId }}-{{ inventory_hostname }}"
        template_name: "{{ jsonData.deploy.vcCluster }}-{{ template_map[buildInfo.esx].split('/')[4] }}"
        cvm_template: "{{ jsonData.deploy.vcCluster }}-{{ template_map[buildInfo.scvm].split('/')[4] }}-controller"
        storfsRelease: "{{ hostvars[inventory_hostname]['storfsRelease'] }}"
        storfsBuild: "{{ hostvars[inventory_hostname]['storfsBuild'] }}"
        replRoleType: "{{ cluster.replRoleType | default(omit) }}"
        buildUrl: "{{ options.build | default(buildInfo.build, True) | regex_replace('latest', storfsBuild) }}"
        powerVMS: "{{ powerVMS | default(true) }}"

    - name: Revert to a snapshot
      local_action:
        module: vmware_guest_snapshot
        hostname: "{{ jsonData.deploy.vcHost }}"
        username: "{{ jsonData.deploy.vcUser }}"
        password: "{{ jsonData.deploy.vcPass }}"
        validate_certs: no
        datacenter: "{{ jsonData.deploy.vcDatacenter }}"
        folder: "/{{ jsonData.deploy.vcDatacenter }}/vm/{{ jsonData.deploy.vcCluster }}-simulators"
        name: "{{ vm_name }}"
        state: revert
        snapshot_name: clean
      when: powerVMS

    - name: Power on VM
      local_action:
        module: vmware_guest
        hostname: "{{ jsonData.deploy.vcHost }}"
        username: "{{ jsonData.deploy.vcUser }}"
        password: "{{ jsonData.deploy.vcPass }}"
        validate_certs: no
        cluster: "{{ jsonData.deploy.vcCluster }}"
        datacenter: "{{ jsonData.deploy.vcDatacenter }}"
        folder: "/{{ jsonData.deploy.vcDatacenter }}/vm/{{ jsonData.deploy.vcCluster }}-simulators"
        name: "{{ vm_name }}"
        state: poweredon
      when: powerVMS

    - name: Power off VM
      local_action:
        module: vmware_guest
        hostname: "{{ jsonData.deploy.vcHost }}"
        username: "{{ jsonData.deploy.vcUser }}"
        password: "{{ jsonData.deploy.vcPass }}"
        validate_certs: no
        cluster: "{{ jsonData.deploy.vcCluster }}"
        datacenter: "{{ jsonData.deploy.vcDatacenter }}"
        folder: "/{{ jsonData.deploy.vcDatacenter }}/vm/{{ jsonData.deploy.vcCluster }}-simulators"
        name: "{{ vm_name }}"
        state: poweredoff
      when: not powerVMS
